package edu.wmich.cs.aut.arlt14;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Lin Cheng on 1/11/17.
 */
public class Main {
    private JPanel panel1;
    private JCheckBox convertImageToGrayscaleCheckBox;
    private JButton saveButton;
    private JButton OKButton;
    private JTextField textField1;

    private boolean convert = false;
    private int angle = 0;
    private Image image = new Image();


    public Main() {
        convertImageToGrayscaleCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onCheckBox(e);
            }
        });
        textField1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onSlider(e);
            }
        });
        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onSave(e);
            }
        });
        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onOK(e);
            }
        });

    }

    private void onCheckBox(ActionEvent e) {
        convert = convertImageToGrayscaleCheckBox.isSelected();
    }

    private void onSlider(ActionEvent e) {
        Main.this.angle = Integer.parseInt(textField1.getText());
        System.out.println("convert is " + convert + ", angle is " + Main.this.angle);
    }

    private void onSave(ActionEvent e) {
        UserSettings.RotationAngle = angle;
    }

    private void onOK(ActionEvent e) {
        if (convert) {
            image.convertToGrayscale();
            image = null;
        }
        if (angle > 0) {
            image.rotate(angle);
        }

    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("Main");
        frame.setContentPane(new Main().panel1);
        frame.setDefaultCloseOperation(3);
        frame.pack();
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Rotate Image");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("15 Degrees");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        OKButton = new JButton();
        OKButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(OKButton, gbc);
        convertImageToGrayscaleCheckBox = new JCheckBox();
        convertImageToGrayscaleCheckBox.setText("Convert Image to Grayscale");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(convertImageToGrayscaleCheckBox, gbc);
        textField1 = new JTextField();
        textField1.setText("10");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(textField1, gbc);
        saveButton = new JButton();
        saveButton.setText("Save");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(saveButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}


class UserSettings {
    public static int RotationAngle = 0;
}

class Image {
    public void convertToGrayscale() {
        System.out.println("convert image to gray scale");
    }

    public void rotate(int angle) {
        System.out.println("rotate image angle: " + angle);
    }
}